# Generated by Django 3.0.8 on 2020-10-27 12:33

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201027_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default/def.jpg', null=True, upload_to=users.models.DefineUserPathImages),
        ),
    ]
