# Generated by Django 3.0.8 on 2020-10-27 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201027_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='user',
            name='total_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
