# Generated by Django 3.0.8 on 2020-11-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20201113_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
