# Generated by Django 3.0.8 on 2020-11-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
