# Generated by Django 3.0.8 on 2020-11-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренд'},
        ),
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'Характеристика продукта'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='typeofproduct',
            options={'verbose_name': 'Тип продукта', 'verbose_name_plural': 'Тип'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='suffix',
            field=models.CharField(max_length=100, verbose_name='Единица измерения'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
