# Generated by Django 3.0.8 on 2020-11-02 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201102_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='typeofproduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.TypeOfProduct'),
        ),
    ]
