# Generated by Django 3.0.8 on 2020-11-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_characteristic_typeofproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
