# Generated by Django 3.0.8 on 2020-11-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201106_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='typeof',
        ),
        migrations.AddField(
            model_name='product',
            name='typeof',
            field=models.ManyToManyField(to='products.TypeOfProduct', verbose_name='Тип продукта'),
        ),
    ]
