# Generated by Django 3.0.8 on 2020-11-06 07:18

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201106_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_foldername_for_categoryimage, verbose_name='Фото для категории'),
        ),
    ]
