# Generated by Django 3.0.8 on 2020-11-06 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_typeofproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='typeofproduct',
        ),
    ]
