# Generated by Django 3.0.8 on 2020-11-06 10:04

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_characteristic_typeofproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='typeof',
            field=models.ManyToManyField(related_name='products', to='products.TypeOfProduct', verbose_name='Тип продукта'),
        ),
        migrations.AlterField(
            model_name='typeofproduct',
            name='image',
            field=models.ImageField(blank=True, default='default/default.jpeg', null=True, upload_to=products.models.get_foldername_for_categoryimage, verbose_name='Фото для категории'),
        ),
    ]
