# Generated by Django 3.0.8 on 2020-11-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201106_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='typeofproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.TypeOfProduct'),
        ),
    ]
