# Generated by Django 3.0.8 on 2020-11-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_subcategory_typeofproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Под-категория', 'verbose_name_plural': 'Под-категории'},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='typeofproduct',
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ManyToManyField(related_name='products', to='products.SubCategory'),
        ),
    ]
